version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: lootopia-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/lootopia?schema=public"
    depends_on:
      - postgres
    networks:
      - lootopia-network

  postgres:
    image: postgres:15
    container_name: lootopia-postgres
    restart: always
    environment:
      POSTGRES_DB: lootopia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lootopia-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lootopia-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres
    networks:
      - lootopia-network

  prisma-studio:
    image: node:20
    container_name: lootopia-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: sh -c "npm install && npx prisma studio --browser none --port 5555"
    depends_on:
      - postgres
    networks:
      - lootopia-network

networks:
  lootopia-network:


volumes:
  postgres_data:
