version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: lootopia-backend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    depends_on:
      - postgres
    networks:
      - lootopia-network

  postgres:
    image: postgres:15
    container_name: lootopia-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRE_DB}
      POSTGRES_USER: ${POSTGRE_USER}
      POSTGRES_PASSWORD: ${POSTGRE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lootopia-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lootopia-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - lootopia-network

  prisma-studio:
    image: node:20
    container_name: lootopia-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    command: sh -c "npm install && npx prisma studio --browser none --port 5555"
    depends_on:
      - postgres
    networks:
      - lootopia-network

networks:
  lootopia-network:


volumes:
  postgres_data:
