version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: lootopia-backend
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY_CLOUDINARY: ${API_KEY_CLOUDINARY}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lootopia-network

  postgres:
    image: postgres:15
    container_name: lootopia-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lootopia-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: lootopia-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - lootopia-network

  prisma-studio:
    image: node:20
    container_name: lootopia-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    command: sh -c "npm install && npx prisma studio --browser none --port 5555"
    depends_on:
      - postgres
    networks:
      - lootopia-network

networks:
  lootopia-network:


volumes:
  postgres_data:
